import '../globals.css';

export const metadata = {
  title: 'My awesome site!',
  description: 'Generated by next + sanity'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
